/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload Model
         * @description Upload a mesh file; 422 if it cannot be made manifold.
         *
         *     A plain `def` so the (blocking) read and load run in the threadpool. Models evicted from the
         *     store to make room have their live jobs cancelled and their slice artifacts dropped.
         */
        post: operations["upload_model"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/models/{model_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Model
         * @description Return an uploaded model's metadata.
         */
        get: operations["get_model"];
        put?: never;
        post?: never;
        /**
         * Delete Model
         * @description Delete a model, cancel its live jobs, and drop every slice artifact derived from it.
         */
        delete: operations["delete_model"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/models/{model_id}/mesh.glb": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Model Glb
         * @description Return the model mesh in the model frame as binary glTF.
         */
        get: operations["get_model_glb"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/models/{model_id}/plan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Plan Model
         * @description Compute the cut plan synchronously (live preview).
         */
        post: operations["plan_model"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/models/{model_id}/slice": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Slice Model
         * @description Submit a slice job; supersedes any live job for the same model.
         */
        post: operations["slice_model"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Job
         * @description Return a snapshot of a job.
         */
        get: operations["get_job"];
        put?: never;
        post?: never;
        /**
         * Cancel Job
         * @description Cancel a job (idempotent) and return its snapshot.
         */
        delete: operations["cancel_job"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}/pieces.glb": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Pieces Glb
         * @description Return every piece in the model frame; node name = piece_id.
         */
        get: operations["get_pieces_glb"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}/pieces/{piece_id}.stl": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Piece Stl
         * @description Return one piece as STL in the print frame (min z = 0, xy-centred).
         */
        get: operations["get_piece_stl"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}/download.zip": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download Zip
         * @description Return every piece STL (print frame) plus manifest.json (= SliceResult).
         */
        get: operations["download_zip"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/presets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Presets
         * @description Return the built-in printer presets.
         */
        get: operations["list_presets"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness probe.
         */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Axis
         * @enum {string}
         */
        Axis: "x" | "y" | "z";
        /**
         * AxisCuts
         * @description Interior cut positions per axis, in model coordinates.
         */
        AxisCuts: {
            /** X */
            x?: number[];
            /** Y */
            y?: number[];
            /** Z */
            z?: number[];
        };
        /** Body_upload_model */
        Body_upload_model: {
            /** File */
            file: string;
            /**
             * Scale
             * @default 1
             */
            scale: number;
        };
        /** Bounds */
        Bounds: {
            /** Min */
            min: [
                number,
                number,
                number
            ];
            /** Max */
            max: [
                number,
                number,
                number
            ];
        };
        /** Cell */
        Cell: {
            index: components["schemas"]["CellIndex"];
            bounds: components["schemas"]["Bounds"];
        };
        /** CellIndex */
        CellIndex: {
            /** I */
            i: number;
            /** J */
            j: number;
            /** K */
            k: number;
        };
        /**
         * CellLimits
         * @description Per-axis maximum cell size the planner may emit, and the minimum spacing between cuts.
         */
        CellLimits: {
            /** Max Cell */
            max_cell: [
                number,
                number,
                number
            ];
            /**
             * Min Cell
             * @default 1
             */
            min_cell: number;
        };
        /** CutInterface */
        CutInterface: {
            /** Id */
            id: string;
            axis: components["schemas"]["Axis"];
            /** Position */
            position: number;
            lower: components["schemas"]["CellIndex"];
            upper: components["schemas"]["CellIndex"];
            frame: components["schemas"]["PlaneFrame"];
            /** Extent U */
            extent_u: number;
            /** Extent V */
            extent_v: number;
            /** Interior Edges */
            interior_edges?: ("u_min" | "u_max" | "v_min" | "v_max")[];
        };
        /** CutPlan */
        CutPlan: {
            bounds: components["schemas"]["Bounds"];
            limits: components["schemas"]["CellLimits"];
            cuts: components["schemas"]["AxisCuts"];
            /** Cells */
            cells: components["schemas"]["Cell"][];
            /** Interfaces */
            interfaces: components["schemas"]["CutInterface"][];
            /** Warnings */
            warnings?: components["schemas"]["SliceWarning"][];
        };
        /**
         * DovetailJointSpec
         * @description A sliding dovetail: trapezoid in the (u, normal) plane extruded along v through the cell.
         *
         *     Pieces interlock against pull-apart along the normal and assemble by sliding along v.
         */
        DovetailJointSpec: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "dovetail";
            /**
             * Neck Width
             * @default 8
             */
            neck_width: number;
            /**
             * Head Width
             * @default 12
             */
            head_width: number;
            /**
             * Depth
             * @default 6
             */
            depth: number;
            /**
             * Clearance
             * @default 0.15
             */
            clearance: number;
            /**
             * Edge Margin
             * @default 3
             */
            edge_margin: number;
            /**
             * Spacing
             * @default 60
             */
            spacing: number;
        };
        /**
         * DowelJointSpec
         * @description A cylindrical registration pin straddling the cut plane.
         */
        DowelJointSpec: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "dowel";
            /**
             * Diameter
             * @default 8
             */
            diameter: number;
            /**
             * Depth
             * @default 6
             */
            depth: number;
            /**
             * Clearance
             * @default 0.15
             */
            clearance: number;
            /**
             * Edge Margin
             * @default 3
             */
            edge_margin: number;
            /**
             * Spacing
             * @default 40
             */
            spacing: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * Job
         * @description Mutable: the runner updates progress in place (under its own lock).
         */
        Job: {
            /** Job Id */
            job_id: string;
            /** Model Id */
            model_id: string;
            /** @default queued */
            status: components["schemas"]["JobStatus"];
            /**
             * Progress
             * @default 0
             */
            progress: number;
            /**
             * Step
             * @default queued
             */
            step: string;
            result?: components["schemas"]["SliceResult"] | null;
            /** Error */
            error?: string | null;
        };
        /**
         * JobStatus
         * @enum {string}
         */
        JobStatus: "queued" | "running" | "done" | "failed" | "cancelled";
        /** JointInfo */
        JointInfo: {
            /** Interface Id */
            interface_id: string;
            /** Kind */
            kind: string;
            /** Male Piece */
            male_piece: string;
            /** Female Piece */
            female_piece: string;
            placement: components["schemas"]["Placement"];
        };
        /**
         * MaleSide
         * @enum {string}
         */
        MaleSide: "lower" | "upper";
        /** MeshAsset */
        MeshAsset: {
            /** Model Id */
            model_id: string;
            /** Filename */
            filename: string;
            /** Scale */
            scale: number;
            /** Triangle Count */
            triangle_count: number;
            bounds: components["schemas"]["Bounds"];
            /** Volume */
            volume: number;
            /** Warnings */
            warnings?: components["schemas"]["SliceWarning"][];
        };
        /** NoJointSpec */
        NoJointSpec: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            kind: "none";
        };
        /** PartitionSpec */
        PartitionSpec: {
            cuts?: components["schemas"]["AxisCuts"] | null;
            /**
             * Bed Margin
             * @default 2
             */
            bed_margin: number;
        };
        /** PieceInfo */
        PieceInfo: {
            /** Piece Id */
            piece_id: string;
            cell: components["schemas"]["CellIndex"];
            /**
             * Component
             * @default 0
             */
            component: number;
            bounds: components["schemas"]["Bounds"];
            /** Volume */
            volume: number;
            /** Triangle Count */
            triangle_count: number;
            /** Component Count */
            component_count: number;
            /** Fits Bed */
            fits_bed: boolean;
            /** Print Offset */
            print_offset: [
                number,
                number,
                number
            ];
        };
        /** Placement */
        Placement: {
            /** U */
            u: number;
            /** V */
            v: number;
            /**
             * Rotation
             * @default 0
             */
            rotation: number;
        };
        /**
         * PlaneFrame
         * @description An interface plane: origin on the plane, unit normal from the lower to the upper cell,
         *     and in-plane unit axes u, v (right-handed: u cross v = normal).
         */
        PlaneFrame: {
            /** Origin */
            origin: [
                number,
                number,
                number
            ];
            /** Normal */
            normal: [
                number,
                number,
                number
            ];
            /** U */
            u: [
                number,
                number,
                number
            ];
            /** V */
            v: [
                number,
                number,
                number
            ];
        };
        /** PrintVolume */
        PrintVolume: {
            /** X */
            x: number;
            /** Y */
            y: number;
            /** Z */
            z: number;
        };
        /** PrinterPreset */
        PrinterPreset: {
            /** Name */
            name: string;
            print_volume: components["schemas"]["PrintVolume"];
        };
        /** SliceResult */
        SliceResult: {
            /** Job Id */
            job_id: string;
            /** Model Id */
            model_id: string;
            spec: components["schemas"]["SliceSpec"];
            plan: components["schemas"]["CutPlan"];
            /** Pieces */
            pieces: components["schemas"]["PieceInfo"][];
            /** Joints */
            joints: components["schemas"]["JointInfo"][];
            stats: components["schemas"]["SliceStats"];
            /** Warnings */
            warnings?: components["schemas"]["SliceWarning"][];
        };
        /** SliceSpec */
        SliceSpec: {
            print_volume: components["schemas"]["PrintVolume"];
            /**
             * @default {
             *       "bed_margin": 2
             *     }
             */
            partition: components["schemas"]["PartitionSpec"];
            /**
             * Joint
             * @default {
             *       "kind": "none"
             *     }
             */
            joint: components["schemas"]["NoJointSpec"] | components["schemas"]["DowelJointSpec"] | components["schemas"]["DovetailJointSpec"];
            /** @default lower */
            male_side: components["schemas"]["MaleSide"];
        };
        /** SliceStats */
        SliceStats: {
            /** Piece Count */
            piece_count: number;
            /** Input Volume */
            input_volume: number;
            /** Output Volume */
            output_volume: number;
            /** Max Overlap Volume */
            max_overlap_volume: number;
            /** Duration S */
            duration_s: number;
        };
        /** SliceWarning */
        SliceWarning: {
            code: components["schemas"]["WarningCode"];
            /** Message */
            message: string;
            /** Subject */
            subject?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * WarningCode
         * @enum {string}
         */
        WarningCode: "cell_oversize" | "piece_oversize" | "disconnected_piece" | "no_contact_for_joint" | "joint_clipped" | "assembly_conflict" | "vertices_merged";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    upload_model: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_model"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeshAsset"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_model: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                model_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeshAsset"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_model: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                model_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_model_glb: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                model_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Model mesh as GLB. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "model/gltf-binary": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    plan_model: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                model_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SliceSpec"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CutPlan"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    slice_model: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                model_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SliceSpec"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_job: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_pieces_glb: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description All pieces as one scene. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "model/gltf-binary": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_piece_stl: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
                piece_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One piece, print frame. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "model/stl": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_zip: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description STLs + manifest.json. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/zip": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_presets: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PrinterPreset"][];
                };
            };
        };
    };
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
